[package]
name = "zm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
dirs = "2.0"

[[bin]]
name = "zoom"
path = "src/main.rs"
